#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import template_builder as build_template_cpp

env.CommandNoCache(
    "templates.gen.h",
    sorted(Glob("*/*.h") + Glob("*/*.cpp") + Glob("*/*.meta"), key=str),
    env.Run(build_template_cpp.make_templates),
)
